---
title: "Untitled"
author: "Kevin"
date: "July 9, 2019"
output: html_document
---
```{r}
library('ggplot2')
library('forecast')
library('tseries')
library('outliers')
library('readxl')
library('vars')
library('dplyr')
library('plyr')
library('boot')
library('fpp')
library('xts')
library('VAR.etp')
library('TSA')
library('stats')
library('OutliersO3')
library('OutlierDetection')
library('Hmisc')
library('writexl')
library('openxlsx')
library('xlsx')
```

```{r}
x='CUTLERY KIT'
forecast_md_1<- function(x){
  first_item <- subset(df2,(x==df2$NEW_NAME_MERGE)==TRUE)
  return(first_item)
}
forecast_md_2<-function(x){
  df3=df2[df2$NEW_NAME_MERGE!=x,]
  cov_item <- aggregate(df3$sum_quantity_adj_edit,sum,by=list(df3$delivery_date))
  return(cov_item)}

quant_1=forecast_md_1(x)[,2:3]
quant_2=forecast_md_2(x)[,2]
quant_3=cbind(quant_1,quant_2)
quant=subset(quant_3[1:61,])
names(quant)[2]<-'M'
names(quant)[3]<-'N'

quant_ts=ts(quant[,2],end=c(2019,1),frequency = 12)
dx_1=ts(quant[,2:3],end=c(2019,1),frequency = 12)

k <- length(quant_ts)-45
n <- length(quant_ts)
quant_ts
p <- 12
H <- 1
mae_1_sarima <- matrix(NA,1,n)
mae_2_sarima <- matrix(NA,1,n)
mae_1_arima <- matrix(NA,1,n)
mae_2_arima <- matrix(NA,1,n)
mae_1_hw <- matrix(NA,1,n)
mae_2_hw <- matrix(NA,1,n)
mae_1_hw_1 <- matrix(NA,1,n)
mae_2_hw_1 <- matrix(NA,1,n)
mae_1_ets <- matrix(NA,1,n)
mae_2_ets <- matrix(NA,1,n)
mae_1_var <- matrix(NA,1,n)
mae_2_var <- matrix(NA,1,n)
mae_1_sarimax <- matrix(NA,1,n)
mae_2_sarimax <- matrix(NA,1,n)
st <- tsp(quant_ts)[1]+(k-1)/p
l=BoxCox.lambda(dx_1[,1])
plot.ts(BoxCox(dx_1[,1], lambda = l))
?auto.arima
sarima_f=function(x,h){
fit_1_sarima<-auto.arima(x,D=1,max.D = 10, stepwise=FALSE,seasonal = TRUE,ic='aic',stationary = FALSE,allowdrift  = TRUE,allowmean=FALSE,lambda=l,biasadj = FALSE)
fct_1_sarima<-forecast(fit_1_sarima,h)
return(fct_1_sarima)}

plot(sarima_f(quant_ts,60))
summary(sarima_f(quant_ts,60))

arima_f=function(x,h){
fit_1_arima<-auto.arima(x,D = 0, max.D = 10, stepwise=FALSE,seasonal = FALSE,ic='aic',stationary = FALSE,allowdrift  = TRUE,lambda = l,biasadj = TRUE)
fct_1_arima<-forecast(fit_1_arima,h)
return(fct_1_arima)}

#plot(arima_f(quant_ts,60))

hw_f_1=function(x,h){
fit_1_hw<-hw(x,h,seasonal = c('additive'))
fct_1_hw<-forecast(fit_1_hw,h)
return(fct_1_hw)}
#plot(hw_f_1(quant_ts,60))

hw_f=function(x,h){
fit_1_hw<-hw(x,h,damped=TRUE,seasonal = c('multiplicative'))
fct_1_hw<-forecast(fit_1_hw,h)
return(fct_1_hw)}

#plot(hw_f(quant_ts,60))

ets_f=function(x,h){
fit_1_ets<-ets(x,model="ZZZ",allow.multiplicative.trend=FALSE)
fct_1_ets<-forecast(fit_1_ets,h)
return(fct_1_ets)}

#plot(ets_f(quant_ts,60))

var_f=function(x,h){
fit_1_var<-VAR(x, lag.max=10 ,ic = "AIC")
fct_1_var<-forecast(fit_1_var,h)
return(fct_1_var)}
#plot(var_f(dx_1,60))

sarimax_f=function(x,y,h){
  fit_1_sarimax<-auto.arima(x[,1],xreg=x[,2],D=1,max.D = 10, stepwise=FALSE,seasonal = TRUE,ic='aic',stationary = FALSE,allowdrift  = TRUE,allowmean=TRUE,lambda = l,biasadj = TRUE)
  fct_1_sarimax<-forecast(fit_1_sarimax,xreg=y[,2])
  return(fct_1_sarimax)}

  fit_reg_1 <- auto.arima(dx_1[,2],D=1,seasonal = TRUE)
  x_1=forecast(fit_reg_1,60)$mean
  fit_reg_2 <- auto.arima(dx_1[,1],xreg = dx_1[,2],D=1,stepwise=FALSE,seasonal = TRUE,ic='aic',stationary = FALSE,allowdrift  = TRUE,lambda = 'auto')
  fct_reg <- forecast(fit_reg_2,xreg=x_1)
  summary(fct_reg)
  plot(fct_reg,sub=x)
#resultm[[x]]=summary(var_f(dx_1,60)$forecast$M)
#resultm[[x]]=summary(sarima_f(dx_1[,1],60))
#resultm[[x]]=summary(fct_reg)
?BoxCox
```
```{r}
for(i in 1:(n-k-1))
{
  cv_train_1<-window(quant_ts,end=st+i/p)
  cv_train_2<-window(quant_ts,start=st+(i-k+1)/p,end=st+i/p)
  cv_train_3<-window(dx_1,end=st+i/p)
  cv_train_4<-window(dx_1,start=st+(i-k+1)/p,end=st+i/p)
  cv_test<-window(quant_ts,start=st+(i+1)/p,end=st+(i+1)/p)
  cv_test_1<-window(dx_1,start=st+(i+1)/p,end=st+(i+1)/p)
  if(i<50) {
  #cat(c("*** CV", i,":","len(Expanding Window):",length(train_1), "len(Sliding Window):",length(train_2), "len(Test):",length(test),'\n'  ))
  cat(c("*** TRAIN -  Expanding WIndow:",tsp(cv_train_1)[1],'-',tsp(cv_train_1)[2],'\n'))
  cat(c("*** TRAIN - Sliding WIndow:",tsp(cv_train_2)[1],'-',tsp(cv_train_2)[2],'\n'))
  cat(c("*** TEST:",tsp(cv_test)[1],'-',tsp(cv_test)[2],'\n'))
  cat("*************************** \n \n")}

  mae_1_sarima[1,i] <- abs(as.numeric(sarima_f(cv_train_1,H)[['mean']])-cv_test)
  mae_2_sarima[1,i] <- abs(as.numeric(sarima_f(cv_train_2,H)[['mean']])-cv_test)

  
  mae_1_arima[1,i] <- abs(as.numeric(arima_f(cv_train_1,H)[['mean']])-cv_test)
  mae_2_arima[1,i] <- abs(as.numeric(arima_f(cv_train_2,H)[['mean']])-cv_test)


  mae_1_hw[1,i] <- abs(as.numeric(hw_f(cv_train_1,H)[['mean']])-cv_test)
  mae_2_hw[1,i] <- abs(as.numeric(hw_f(cv_train_2,H)[['mean']])-cv_test)

  mae_1_hw_1[1,i] <- abs(as.numeric(hw_f_1(cv_train_1,H)[['mean']])-cv_test)
  mae_2_hw_1[1,i] <- abs(as.numeric(hw_f_1(cv_train_2,H)[['mean']])-cv_test)
  
  mae_1_ets[1,i] <- abs(as.numeric(ets_f(cv_train_1,H)[['mean']])-cv_test)
  mae_2_ets[1,i] <- abs(as.numeric(ets_f(cv_train_2,H)[['mean']])-cv_test)


  mae_1_var[1,i] <- abs(as.numeric(var_f(cv_train_3,H)$forecast$M$mean)-cv_test)
  mae_2_var[1,i] <- abs(as.numeric(var_f(cv_train_4,H)$forecast$M$mean)-cv_test)


  mae_1_sarimax[1,i] <- abs(as.numeric(sarimax_f(cv_train_3,cv_test_1,H)[['mean']])-cv_test)
  mae_2_sarimax[1,i] <- abs(as.numeric(sarimax_f(cv_train_4,cv_test_1,H)[['mean']])-cv_test)

}

error_sarima_exp<-mean(mae_1_sarima,na.rm = TRUE)
error_sarima_rol<-mean(mae_2_sarima,na.rm = TRUE)
error_sarima<-1/2*(error_sarima_exp+error_sarima_rol)
error_arima_exp<-mean(mae_1_arima,na.rm = TRUE)
error_arima_rol<-mean(mae_2_arima,na.rm = TRUE)
error_arima<-1/2*(error_arima_exp+error_arima_rol)
error_hw_exp<-mean(mae_1_hw,na.rm = TRUE)
error_hw_rol<-mean(mae_2_hw,na.rm = TRUE)
error_hw<-1/2*(error_hw_exp+error_hw_rol)
error_hw_exp_1<-mean(mae_1_hw_1,na.rm = TRUE)
error_hw_rol_1<-mean(mae_2_hw_1,na.rm = TRUE)
error_hw_1<-1/2*(error_hw_exp_1+error_hw_rol_1)
error_ets_exp<-mean(mae_1_ets,na.rm = TRUE)
error_ets_rol<-mean(mae_2_ets,na.rm = TRUE)
error_ets<-1/2*(error_ets_exp+error_ets_rol)
error_var_exp<-mean(mae_1_var,na.rm = TRUE)
error_var_rol<-mean(mae_2_var,na.rm = TRUE)
error_var<-1/2*(error_var_exp+error_var_rol)
error_sarimax_exp<-mean(mae_1_sarimax,na.rm = TRUE)
error_sarimax_rol<-mean(mae_2_sarimax,na.rm = TRUE)
error_sarimax<-1/2*(error_sarimax_exp+error_sarimax_rol)
?auto.arima
err_term<-c('arima_f'=error_arima,'sarima_f'=error_sarima,'sarimax_f'=error_sarimax,'hw_f'=error_hw,'var_f'=error_var,'ets_f'=error_ets,'hw_f_1'=error_hw_1)
err_term
best_name=names(err_term[which.min(err_term)])
```

```{r}
result_11=list()

result_11[[x]]=resultm[[x]][,-2:-3]

write.xlsx(result_11,file='results_98.xlsx')

```


