---
title: "Untitled"
author: "Kevin"
date: "July 3, 2019"
output: html_document
---
```{r}
library('ggplot2')
library('forecast')
library('tseries')
library('outliers')
library('readxl')
library('vars')
library('dplyr')
library('plyr')
library('boot')
library('fpp')
library('xts')
library('VAR.etp')
library('TSA')
library('stats')
library('OutliersO3')
library('OutlierDetection')
library('Hmisc')
library('writexl')
library('openxlsx')
library('xlsx')
```
```{r}
df <- read_excel("C:/Users/kren/Downloads/df.xlsx",sheet = "Sheet1")
df2<-df[,2:4]
```




```{r}
name_list=unique(df2$NEW_NAME_MERGE)

result=list()

for (x in name_list)
{

forecast_md_1<- function(x){
  first_item <- subset(df2,(x==df2$NEW_NAME_MERGE)==TRUE)
  return(first_item)
}
forecast_md_2<-function(x){
  #cov_item <- subset(df2,grepl(y,df2$NEW_NAME_MERGE)==TRUE)
  df3=df2[df2$NEW_NAME_MERGE!=x,]
  cov_item <- aggregate(df3$sum_quantity_adj_edit,sum,by=list(df3$delivery_date))
  return(cov_item)}

  if (nrow(forecast_md_1(x))!=nrow(forecast_md_2(x))) 
    {next}
{
    quant_1=forecast_md_1(x)[,2:3]
    quant_2=forecast_md_2(x)[,2]
    quant=cbind(quant_1,quant_2)
    names(quant)[2]<-'M'
    names(quant)[3]<-'N'

quant_ts=ts(quant[,2],end=c(2019,1),frequency = 12)
dx_1=ts(quant[,2:3],end=c(2019,1),frequency = 12)

k <- length(quant_ts)-6
n <- length(quant_ts)
quant_ts
p <- 12
H <- 12
mae_1_sarima <- matrix(NA,n-k,n-k)
mae_2_sarima <- matrix(NA,n-k,n-k)
mae_1_arima <- matrix(NA,n-k,n-k)
mae_2_arima <- matrix(NA,n-k,n-k)
mae_1_hw <- matrix(NA,n-k,n-k)
mae_2_hw <- matrix(NA,n-k,n-k)
mae_1_ets <- matrix(NA,n-k,n-k)
mae_2_ets <- matrix(NA,n-k,n-k)
mae_1_var <- matrix(NA,n-k,n-k)
mae_2_var <- matrix(NA,n-k,n-k)
mae_1_sarimax <- matrix(NA,n-k,n-k)
mae_2_sarimax <- matrix(NA,n-k,n-k)
st <- tsp(quant_ts)[1]+(k-2)/p

sarima_f=function(x,h){
fit_1_sarima<-auto.arima(x,D = 1, max.D = 10, stepwise=FALSE,seasonal = TRUE,ic='aic',stationary = FALSE,allowdrift  = TRUE,lambda = NULL,biasadj = TRUE)
fct_1_sarima<-forecast(fit_1_sarima,h)
return(fct_1_sarima)}

arima_f=function(x,h){
fit_1_arima<-auto.arima(x,D = 0, max.D = 10, stepwise=FALSE,seasonal = FALSE,ic='aic',stationary = FALSE,allowdrift  = TRUE,lambda = NULL,biasadj = TRUE)
fct_1_arima<-forecast(fit_1_arima,h)
return(fct_1_arima)}

hw_f=function(x,h){
fit_1_hw<-hw(x,h,seasonal = c('additive'))
fct_1_hw<-forecast(fit_1_hw,h)
return(fct_1_hw)}

ets_f=function(x,h){
fit_1_ets<-ets(x,model="ZZZ")
fct_1_ets<-forecast(fit_1_ets,h)
return(fct_1_ets)}

var_f=function(x,h){
fit_1_var<-VAR(x, lag.max=10 ,ic = "AIC")
fct_1_var<-forecast(fit_1_var,h)
return(fct_1_var)}
# fit_1_var<-VAR(dx_1,lag.max=10,ic = "AIC")
# 
# fct_var<-forecast(fit_1_var,60)
# plot(fct_var)
# accuracy(fct_var,d=0,D=1)
# summary(fct_var$forecast$M)
sarimax_f=function(x,y,h){
  fit_1_sarimax<-auto.arima(x[,1],xreg=x[,2],D=1,max.D = 10, stepwise=FALSE,seasonal = TRUE,ic='aic',stationary = FALSE,allowdrift  = TRUE,lambda = NULL,biasadj = TRUE)
  fct_1_sarimax<-forecast(fit_1_sarimax,xreg=y[,2])
  return(fct_1_sarimax)}



for(i in 1:(n-k))
{
  cv_train_1<-window(quant_ts,end=st+i/p)
  cv_train_2<-window(quant_ts,start=st+(i-k+1)/p,end=st+i/p)
  cv_train_3<-window(dx_1,end=st+i/p)
  cv_train_4<-window(dx_1,start=st+(i-k+1)/p,end=st+i/p)
  cv_test<-window(quant_ts,start=st+(i+1)/p,end=c(2019,1))
  cv_test_1<-window(dx_1,start=st+(i+1)/p,end=c(2019,1))
  # if(i<15) {
  #cat(c("*** CV", i,":","len(Expanding Window):",length(train_1), "len(Sliding Window):",length(train_2), "len(Test):",length(test),'\n'  ))
  # cat(c("*** TRAIN -  Expanding WIndow:",tsp(cv_train_1)[1],'-',tsp(cv_train_1)[2],'\n'))
  # cat(c("*** TRAIN - Sliding WIndow:",tsp(cv_train_2)[1],'-',tsp(cv_train_2)[2],'\n'))
  # cat(c("*** TEST:",tsp(cv_test)[1],'-',tsp(cv_test)[2],'\n'))
  # cat("*************************** \n \n")}

  mae_1_sarima[i,1:length(cv_test)] <- abs(sarima_f(cv_train_1,H)[['mean']]-cv_test)
  mae_2_sarima[i,1:length(cv_test)] <- abs(sarima_f(cv_train_2,H)[['mean']]-cv_test)

  
  mae_1_arima[i,1:length(cv_test)] <- abs(arima_f(cv_train_1,H)[['mean']]-cv_test)
  mae_2_arima[i,1:length(cv_test)] <- abs(arima_f(cv_train_2,H)[['mean']]-cv_test)


  mae_1_hw[i,1:length(cv_test)] <- abs(hw_f(cv_train_1,H)[['mean']]-cv_test)
  mae_2_hw[i,1:length(cv_test)] <- abs(hw_f(cv_train_2,H)[['mean']]-cv_test)


  mae_1_ets[i,1:length(cv_test)] <- abs(ets_f(cv_train_1,H)[['mean']]-cv_test)
  mae_2_ets[i,1:length(cv_test)] <- abs(ets_f(cv_train_2,H)[['mean']]-cv_test)


  mae_1_var[i,1:length(cv_test)] <- abs(var_f(cv_train_3,H)$forecast$M$mean-cv_test)
  mae_2_var[i,1:length(cv_test)] <- abs(var_f(cv_train_4,H)$forecast$M$mean-cv_test)


  mae_1_sarimax[i,1:length(cv_test)] <- abs(sarimax_f(cv_train_3,cv_test_1,H)[['mean']]-cv_test)
  mae_2_sarimax[i,1:length(cv_test)] <- abs(sarimax_f(cv_train_4,cv_test_1,H)[['mean']]-cv_test)

}

error_sarima_exp<-mean(mae_1_sarima,na.rm = TRUE)
error_sarima_rol<-mean(mae_2_sarima,na.rm = TRUE)
error_sarima<-1/2*(error_sarima_exp+error_sarima_rol)
error_arima_exp<-mean(mae_1_arima,na.rm = TRUE)
error_arima_rol<-mean(mae_2_arima,na.rm = TRUE)
error_arima<-1/2*(error_arima_exp+error_arima_rol)
error_hw_exp<-mean(mae_1_hw,na.rm = TRUE)
error_hw_rol<-mean(mae_2_hw,na.rm = TRUE)
error_hw<-1/2*(error_hw_exp+error_hw_rol)
error_ets_exp<-mean(mae_1_ets,na.rm = TRUE)
error_ets_rol<-mean(mae_2_ets,na.rm = TRUE)
error_ets<-1/2*(error_ets_exp+error_ets_rol)
error_var_exp<-mean(mae_1_var,na.rm = TRUE)
error_var_rol<-mean(mae_2_var,na.rm = TRUE)
error_var<-1/2*(error_var_exp+error_var_rol)
error_sarimax_exp<-mean(mae_1_sarimax,na.rm = TRUE)
error_sarimax_rol<-mean(mae_2_sarimax,na.rm = TRUE)
error_sarimax<-1/2*(error_sarimax_exp+error_sarimax_rol)

err_term<-c('arima_f'=error_arima,'sarima_f'=error_sarima,'sarimax_f'=error_sarimax,'hw_f'=error_hw,'var_f'=error_var,'ets_f'=error_ets)
err_term
best_name=names(err_term[which.min(err_term)])
best_f<-match.fun(best_name)

if (grepl('sarimax',best_name)==FALSE)
{
  if (grepl('var',best_name)==FALSE)
  {best_f(dx_1[,1],60)
   plot(best_f(dx_1[,1],60),sub=x)
   result[[x]]<-summary(best_f(dx_1[,1],60))}
  else 
  {best_f(dx_1,60)
   plot(best_f(dx_1,60),sub=x)
   result[[x]]<-summary(best_f(dx_1,60)$forecast$M)}
}else
{
  fit_reg_1 <- auto.arima(dx_1[,2],D=1,seasonal = TRUE)
  x_1=forecast(fit_reg_1,60)$mean
  fit_reg_2 <- auto.arima(dx_1[,1],xreg = dx_1[,2],D=1,seasonal = TRUE)
  fct_reg <- forecast(fit_reg_2,xreg=x_1)
  plot(fct_reg,sub=x)
  result[[x]]<-summary(fct_reg)
}

}
}
```
```{r}

result_11=list()
for (x in name_list)
  result_11[[x]]=result[[x]][,-2:-3]

write.xlsx(result_11,file='results_f3.xlsx')

```

